#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing'

yarn check-format ||
(
    echo 'Its FOKING RAW - Your styling looks disgusting. 
        Prettier Check Failed. Run yarn format, add changes and try commit again.';
    false;
)

yarn check-lint ||
(
    echo 'Get that weak shift out of here!
        Eslint Check Failed. Make the required changes listed above, add changes and try to commit again.';
    false;
)

yarn check-types ||
(
    echo 'Failed Type check.
        Are you seriously trying to write that? Make the changes required above.';
    false;
)

yarn build ||
(
    echo 'Failed To Build.
        Are you seriously trying to write that? Make the changes required above.';
    false;
)

echo 'You win this time... I am commiting this now.';
